-- Create the ClinicApp database
CREATE DATABASE ClinicApp;
GO


USE ClinicApp;
GO


CREATE TABLE Section (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Number INT NOT NULL
);
GO


CREATE TABLE Specialization (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(100) NOT NULL
);
GO


CREATE TABLE Cabine (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Number INT NOT NULL
);
GO


CREATE TABLE Patsient (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Surname NVARCHAR(100) NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    MiddleName NVARCHAR(100),
    Adres NVARCHAR(200) NOT NULL,
    BrithDay DATE NOT NULL,
    Sex NVARCHAR(10) NOT NULL,
    SectionId UNIQUEIDENTIFIER NULL,
    FOREIGN KEY (SectionId) REFERENCES Section(Id)
        ON DELETE SET NULL
);
GO


CREATE TABLE Doctor (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(200) NOT NULL,
    CabineId UNIQUEIDENTIFIER NULL,
    SpecializationId UNIQUEIDENTIFIER NULL,
    SectionId UNIQUEIDENTIFIER NULL,
    FOREIGN KEY (CabineId) REFERENCES Cabine(Id)
        ON DELETE SET NULL,
    FOREIGN KEY (SpecializationId) REFERENCES Specialization(Id)
        ON DELETE SET NULL,
    FOREIGN KEY (SectionId) REFERENCES Section(Id)
        ON DELETE SET NULL
);
GO
